from __future__ import annotations

from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List


def _iso(offset_seconds: int) -> str:
    return (datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc) + timedelta(seconds=offset_seconds)).isoformat()


def get_default_scenario_template() -> Dict[str, Any]:
    """返回默认世界模板（世界观、剧情树、新闻商店），可在前端直接渲染。"""
    return {
        "scenario_id": "DEFAULT_TEMPLATE",
        "background_story": """这是 IFRONTIER 默认世界剧本。

一家名为 BLUEGOLD 的新能源巨头刚刚完成了一笔神秘并购，市场传闻四起。CIVILBANK 作为传统金融巨头试图稳住阵脚，而 NEURALINK 旗下的脑机接口技术公司则在暗处积蓄力量。FOODMART 代表的消费板块似乎被所有人忽视，却在某个假日季隐藏着反转线索。

玩家的目标是在这场信息战争中收集新闻、传播情报、签订合约、交易股票，最终成为掌控全局的终极赢家。""",
        "worldview": {
            "featured_symbols": ["BLUEGOLD", "CIVILBANK", "NEURALINK", "FOODMART"],
            "market_open_note": "09:30 市场开盘，隔夜消息将在开盘瞬间释放。",
            "market_close_note": "16:00 收盘，未消化的传闻将在盘后结算中发酵。",
            "holiday_note": "节假日期间，市场流动性降低，谣言传播效率翻倍。",
            "overview_note": "默认世界：新能源、传统金融、脑机科技、消费板块四方博弈。",
        },
        "news_store_items": [
            {
                "kind": "RUMOR",
                "price_cash": 2000,
                "description": "来源不明的非官方消息，传播力强但可信度存疑。",
                "requires_symbols": False,
                "trigger_mode": "IMMEDIATE",
                "tags": ["news", "base"],
                "rarity": "COMMON",
                "chain_kind": None,
                "chain_defaults": {},
                "chain_tree": [],
                "enabled": True,
            },
            {
                "kind": "LEAK",
                "price_cash": 15000,
                "description": "内部流出的机密文件，极具杀伤力。",
                "requires_symbols": True,
                "trigger_mode": "IMMEDIATE",
                "tags": ["news", "base"],
                "rarity": "RARE",
                "chain_kind": None,
                "chain_defaults": {},
                "chain_tree": [],
                "enabled": True,
            },
            {
                "kind": "REPORT",
                "price_cash": 8000,
                "description": "机构发布的专业分析，对市场预期有显著引导。",
                "requires_symbols": True,
                "trigger_mode": "IMMEDIATE",
                "tags": ["news", "base"],
                "rarity": "UNCOMMON",
                "chain_kind": None,
                "chain_defaults": {},
                "chain_tree": [],
                "enabled": True,
            },
            {
                "kind": "MAJOR_EVENT",
                "price_cash": 100000,
                "description": "足以改变行业格局的重大突发事件。",
                "requires_symbols": True,
                "trigger_mode": "AUTO_CHAIN",
                "tags": ["news", "chain"],
                "rarity": "EPIC",
                "chain_kind": "MAJOR_EVENT",
                "chain_defaults": {"t0_seconds": 60, "omen_interval_seconds": 10, "abort_probability": 0.3, "grant_count": 2, "seed": 1},
                "chain_tree": [
                    {
                        "node_id": "major_node_1",
                        "kind": "RUMOR",
                        "text": "某巨头董事会内部出现激烈分歧，一份神秘并购文件正在流传。",
                        "scheduled_delay_seconds": 10,
                        "activation_prob": 1.0,
                        "symbols": ["BLUEGOLD"],
                        "tags": ["leak", "board"],
                        "truth_payload": {"impact": "up", "sector": "energy"},
                        "parent_node_id": None,
                    },
                    {
                        "node_id": "major_node_2",
                        "kind": "MAJOR_EVENT",
                        "text": "BLUEGOLD 正式官宣收购海外锂矿，供应链格局瞬间改写。",
                        "scheduled_delay_seconds": 35,
                        "activation_prob": 0.85,
                        "symbols": ["BLUEGOLD", "CIVILBANK"],
                        "tags": ["report", "ma"],
                        "truth_payload": {"impact": "up", "volatility": "high"},
                        "parent_node_id": "major_node_1",
                    },
                ],
                "enabled": True,
            },
            {
                "kind": "WORLD_EVENT",
                "price_cash": 500000,
                "description": "影响所有参与者的宏观系统性事件。",
                "requires_symbols": False,
                "trigger_mode": "AUTO_CHAIN",
                "tags": ["news", "chain"],
                "rarity": "LEGENDARY",
                "chain_kind": "WORLD_EVENT",
                "chain_defaults": {"t0_seconds": 15, "omen_interval_seconds": 10, "abort_probability": 0.2, "grant_count": 2, "seed": 2},
                "chain_tree": [
                    {
                        "node_id": "world_node_1",
                        "kind": "RUMOR",
                        "text": "中央银行正在研究针对科技巨头的全新监管框架。",
                        "scheduled_delay_seconds": 15,
                        "activation_prob": 1.0,
                        "symbols": ["NEURALINK", "CIVILBANK"],
                        "tags": ["regulation", "macro"],
                        "truth_payload": {"impact": "mixed"},
                        "parent_node_id": None,
                    },
                    {
                        "node_id": "world_node_2",
                        "kind": "WORLD_EVENT",
                        "text": "新监管法案落地，所有科技股遭遇剧烈波动，市场进入高不确定状态。",
                        "scheduled_delay_seconds": 45,
                        "activation_prob": 0.75,
                        "symbols": ["NEURALINK", "BLUEGOLD", "CIVILBANK"],
                        "tags": ["regulation", "crash"],
                        "truth_payload": {"impact": "volatile", "all_symbols": True},
                        "parent_node_id": "world_node_1",
                    },
                ],
                "enabled": True,
            },
        ],
        "cards": [
            {
                "card_id": "default_root_rumor",
                "kind": "RUMOR",
                "text": "市场传闻：一场围绕新能源与脑机科技的资本博弈正在暗处展开。",
                "symbols": ["BLUEGOLD", "NEURALINK", "CIVILBANK", "FOODMART"],
                "tags": ["intro", "rumor"],
                "truth_payload": {"impact": "neutral", "intro": True},
                "parent_card_id": None,
                "activation_prob": 1.0,
                "scheduled_at": _iso(0),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_leak_1",
                "kind": "LEAK",
                "text": "泄露文件显示 BLUEGOLD 正在与三家海外锂矿谈判。",
                "symbols": ["BLUEGOLD"],
                "tags": ["leak", "energy"],
                "truth_payload": {"impact": "up", "symbol": "BLUEGOLD"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(30),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_report_1",
                "kind": "REPORT",
                "text": "机构报告：CIVILBANK 的传统信贷业务正面临科技公司跨界挤压。",
                "symbols": ["CIVILBANK"],
                "tags": ["report", "finance"],
                "truth_payload": {"impact": "stable", "symbol": "CIVILBANK"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(60),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_major_1",
                "kind": "MAJOR_EVENT",
                "text": "MAJOR：BLUEGOLD 宣布完成百亿并购，股价即将剧烈波动。",
                "symbols": ["BLUEGOLD", "CIVILBANK"],
                "tags": ["major", "ma"],
                "truth_payload": {"impact": "up", "volatility": "high"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(120),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_major_2",
                "kind": "MAJOR_EVENT",
                "text": "后续：BLUEGOLD 并购后首份财报远超预期，供应链议价权显著提升。",
                "symbols": ["BLUEGOLD", "FOODMART"],
                "tags": ["major", "earnings"],
                "truth_payload": {"impact": "up", "follow_up": True},
                "parent_card_id": "default_major_1",
                "activation_prob": 0.9,
                "scheduled_at": _iso(180),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_world_1",
                "kind": "WORLD_EVENT",
                "text": "WORLD：全球监管机构联合发布科技反垄断草案，所有科技股承压。",
                "symbols": ["NEURALINK", "BLUEGOLD"],
                "tags": ["world", "regulation"],
                "truth_payload": {"impact": "volatile", "all_symbols": True},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(300),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
        ],
    }
