from __future__ import annotations

from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List


def _iso(offset_seconds: int) -> str:
    return (datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc) + timedelta(seconds=offset_seconds)).isoformat()


def get_default_scenario_template() -> Dict[str, Any]:
    """返回默认世界模板（世界观、剧情树、新闻商店），可在前端直接渲染。"""
    return {
        "scenario_id": "IFRONTIER_DEFAULT",
        "background_story": """这是 IFRONTIER 默认世界剧本，也是大多数玩家进入的第一条剧情线。

新能源巨头 BLUEGOLD 刚刚完成一笔神秘并购，市场传闻四起。传统金融巨头 CIVILBANK 试图稳住阵脚，脑机科技巨头 NEURALINK 在暗处积蓄力量，而被忽视的消费板块 FOODMART 却在某个假日季隐藏着反转线索。

默认剧情树为完整主线体验：从市场传闻开始，向四条分支展开——BLUEGOLD 的并购与财报、CIVILBANK 的防守与反击、NEURALINK 面临的监管风暴、FOODMART 的消费反转。每个分支有 2~3 层父子节点，部分事件为概率触发，玩家每次进入游戏会观察到不同的剧情展开。

玩家的目标是在这场信息战争中收集新闻、传播情报、签订合约、交易股票，最终成为掌控全局的终极赢家。""",
        "worldview": {
            "featured_symbols": ["BLUEGOLD", "CIVILBANK", "NEURALINK", "FOODMART"],
            "market_open_note": "09:30 市场开盘，隔夜消息将在开盘瞬间释放。",
            "market_close_note": "16:00 收盘，未消化的传闻将在盘后结算中发酵。",
            "holiday_note": "节假日期间，市场流动性降低，谣言传播效率翻倍。",
            "overview_note": "默认世界：新能源、传统金融、脑机科技、消费板块四方博弈。",
        },
        "news_store_items": [
            {
                "kind": "RUMOR",
                "price_cash": 2000,
                "description": "来源不明的非官方消息，传播力强但可信度存疑。",
                "requires_symbols": False,
                "trigger_mode": "IMMEDIATE",
                "tags": ["news", "base"],
                "rarity": "COMMON",
                "chain_kind": None,
                "chain_defaults": {},
                "chain_tree": [],
                "enabled": True,
            },
            {
                "kind": "LEAK",
                "price_cash": 15000,
                "description": "内部流出的机密文件，极具杀伤力。",
                "requires_symbols": True,
                "trigger_mode": "IMMEDIATE",
                "tags": ["news", "base"],
                "rarity": "RARE",
                "chain_kind": None,
                "chain_defaults": {},
                "chain_tree": [],
                "enabled": True,
            },
            {
                "kind": "REPORT",
                "price_cash": 8000,
                "description": "机构发布的专业分析，对市场预期有显著引导。",
                "requires_symbols": True,
                "trigger_mode": "IMMEDIATE",
                "tags": ["news", "base"],
                "rarity": "UNCOMMON",
                "chain_kind": None,
                "chain_defaults": {},
                "chain_tree": [],
                "enabled": True,
            },
            {
                "kind": "MAJOR_EVENT",
                "price_cash": 100000,
                "description": "足以改变行业格局的重大突发事件。",
                "requires_symbols": True,
                "trigger_mode": "AUTO_CHAIN",
                "tags": ["news", "chain"],
                "rarity": "EPIC",
                "chain_kind": "MAJOR_EVENT",
                "chain_defaults": {"t0_seconds": 60, "omen_interval_seconds": 10, "abort_probability": 0.3, "grant_count": 2, "seed": 1},
                "chain_tree": [
                    {
                        "node_id": "major_node_1",
                        "kind": "RUMOR",
                        "text": "某巨头董事会内部出现激烈分歧，一份神秘并购文件正在流传。",
                        "scheduled_delay_seconds": 10,
                        "activation_prob": 1.0,
                        "symbols": ["BLUEGOLD"],
                        "tags": ["leak", "board"],
                        "truth_payload": {"impact": "up", "sector": "energy"},
                        "parent_node_id": None,
                    },
                    {
                        "node_id": "major_node_2",
                        "kind": "MAJOR_EVENT",
                        "text": "BLUEGOLD 正式官宣收购海外锂矿，供应链格局瞬间改写。",
                        "scheduled_delay_seconds": 35,
                        "activation_prob": 0.85,
                        "symbols": ["BLUEGOLD", "CIVILBANK"],
                        "tags": ["report", "ma"],
                        "truth_payload": {"impact": "up", "volatility": "high"},
                        "parent_node_id": "major_node_1",
                    },
                ],
                "enabled": True,
            },
            {
                "kind": "WORLD_EVENT",
                "price_cash": 500000,
                "description": "影响所有参与者的宏观系统性事件。",
                "requires_symbols": False,
                "trigger_mode": "AUTO_CHAIN",
                "tags": ["news", "chain"],
                "rarity": "LEGENDARY",
                "chain_kind": "WORLD_EVENT",
                "chain_defaults": {"t0_seconds": 15, "omen_interval_seconds": 10, "abort_probability": 0.2, "grant_count": 2, "seed": 2},
                "chain_tree": [
                    {
                        "node_id": "world_node_1",
                        "kind": "RUMOR",
                        "text": "中央银行正在研究针对科技巨头的全新监管框架。",
                        "scheduled_delay_seconds": 15,
                        "activation_prob": 1.0,
                        "symbols": ["NEURALINK", "CIVILBANK"],
                        "tags": ["regulation", "macro"],
                        "truth_payload": {"impact": "mixed"},
                        "parent_node_id": None,
                    },
                    {
                        "node_id": "world_node_2",
                        "kind": "WORLD_EVENT",
                        "text": "新监管法案落地，所有科技股遭遇剧烈波动，市场进入高不确定状态。",
                        "scheduled_delay_seconds": 45,
                        "activation_prob": 0.75,
                        "symbols": ["NEURALINK", "BLUEGOLD", "CIVILBANK"],
                        "tags": ["regulation", "crash"],
                        "truth_payload": {"impact": "volatile", "all_symbols": True},
                        "parent_node_id": "world_node_1",
                    },
                ],
                "enabled": True,
            },
        ],
        "cards": [
            {
                "card_id": "default_root_rumor",
                "kind": "RUMOR",
                "text": "市场传闻：一场围绕新能源、传统金融、脑机科技和消费板块的资本博弈正在暗处展开。",
                "symbols": ["BLUEGOLD", "NEURALINK", "CIVILBANK", "FOODMART"],
                "tags": ["intro", "rumor"],
                "truth_payload": {"impact": "neutral", "intro": True},
                "parent_card_id": None,
                "activation_prob": 1.0,
                "scheduled_at": _iso(0),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            # --- Branch A: BLUEGOLD 新能源并购线 (3 levels) ---
            {
                "card_id": "default_leak_1",
                "kind": "LEAK",
                "text": "泄露文件显示 BLUEGOLD 正在与三家海外锂矿谈判，收购金额可能刷新行业纪录。",
                "symbols": ["BLUEGOLD"],
                "tags": ["leak", "energy", "ma"],
                "truth_payload": {"impact": "up", "symbol": "BLUEGOLD"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(30),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_major_1",
                "kind": "MAJOR_EVENT",
                "text": "MAJOR：BLUEGOLD 正式宣布完成百亿锂矿并购，供应链格局瞬间改写。",
                "symbols": ["BLUEGOLD", "CIVILBANK"],
                "tags": ["major", "ma", "energy"],
                "truth_payload": {"impact": "up", "volatility": "high", "symbol": "BLUEGOLD"},
                "parent_card_id": "default_leak_1",
                "activation_prob": 1.0,
                "scheduled_at": _iso(150),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_major_2",
                "kind": "MAJOR_EVENT",
                "text": "后续：BLUEGOLD 并购后首份财报远超预期，上游议价权显著提升。",
                "symbols": ["BLUEGOLD", "FOODMART"],
                "tags": ["major", "earnings", "follow_up"],
                "truth_payload": {"impact": "up", "follow_up": True, "symbol": "BLUEGOLD"},
                "parent_card_id": "default_major_1",
                "activation_prob": 0.9,
                "scheduled_at": _iso(270),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            # --- Branch B: CIVILBANK 传统金融防守线 (3 levels) ---
            {
                "card_id": "default_report_1",
                "kind": "REPORT",
                "text": "机构报告：CIVILBANK 的传统信贷业务正面临科技公司跨界挤压。",
                "symbols": ["CIVILBANK"],
                "tags": ["report", "finance"],
                "truth_payload": {"impact": "stable", "symbol": "CIVILBANK"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(60),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_report_2",
                "kind": "REPORT",
                "text": "CIVILBANK 宣布与三家区域银行组成防御联盟，共同抵御科技金融冲击。",
                "symbols": ["CIVILBANK", "BLUEGOLD"],
                "tags": ["report", "finance", "alliance"],
                "truth_payload": {"impact": "up", "symbol": "CIVILBANK"},
                "parent_card_id": "default_report_1",
                "activation_prob": 0.8,
                "scheduled_at": _iso(180),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_report_3",
                "kind": "REPORT",
                "text": "突发：CIVILBANK 拟收购一家头部支付科技公司，传统金融开始反击。",
                "symbols": ["CIVILBANK", "NEURALINK"],
                "tags": ["report", "finance", "counter_attack"],
                "truth_payload": {"impact": "volatile", "symbol": "CIVILBANK"},
                "parent_card_id": "default_report_2",
                "activation_prob": 0.6,
                "scheduled_at": _iso(300),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            # --- Branch C: NEURALINK 监管风暴线 (3 levels) ---
            {
                "card_id": "default_rumor_tech",
                "kind": "RUMOR",
                "text": "传闻：监管机构正在研究针对脑机接口与科技巨头的全新审查框架。",
                "symbols": ["NEURALINK", "BLUEGOLD"],
                "tags": ["rumor", "regulation", "tech"],
                "truth_payload": {"impact": "mixed", "symbol": "NEURALINK"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(90),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_world_tech_1",
                "kind": "WORLD_EVENT",
                "text": "WORLD：全球主要监管机构联合发布科技反垄断草案，科技股全面承压。",
                "symbols": ["NEURALINK", "BLUEGOLD", "CIVILBANK"],
                "tags": ["world", "regulation", "draft"],
                "truth_payload": {"impact": "volatile", "all_symbols": True},
                "parent_card_id": "default_rumor_tech",
                "activation_prob": 0.85,
                "scheduled_at": _iso(210),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_world_tech_2",
                "kind": "WORLD_EVENT",
                "text": "后续：反垄断法案进入快速听证程序，科技巨头股价进入高波动窗口。",
                "symbols": ["NEURALINK", "BLUEGOLD"],
                "tags": ["world", "regulation", "hearing"],
                "truth_payload": {"impact": "volatile", "all_symbols": True},
                "parent_card_id": "default_world_tech_1",
                "activation_prob": 0.7,
                "scheduled_at": _iso(330),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            # --- Branch D: FOODMART 消费反转线 (3 levels) ---
            {
                "card_id": "default_rumor_food",
                "kind": "RUMOR",
                "text": "假日季传闻：消费板块 FOODMART 被机构低估，可能隐藏业绩反转线索。",
                "symbols": ["FOODMART"],
                "tags": ["rumor", "consumer", "holiday"],
                "truth_payload": {"impact": "neutral", "symbol": "FOODMART"},
                "parent_card_id": "default_root_rumor",
                "activation_prob": 1.0,
                "scheduled_at": _iso(120),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_food_event",
                "kind": "REPORT",
                "text": "FOODMART 假日季销售数据超预期，供应链恢复带动利润率回升。",
                "symbols": ["FOODMART", "BLUEGOLD"],
                "tags": ["report", "consumer", "earnings"],
                "truth_payload": {"impact": "up", "symbol": "FOODMART"},
                "parent_card_id": "default_rumor_food",
                "activation_prob": 0.8,
                "scheduled_at": _iso(240),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
            {
                "card_id": "default_food_major",
                "kind": "MAJOR_EVENT",
                "text": "MAJOR：FOODMART 成为 BLUEGOLD 与 CIVILBANK 争夺的收购目标，消费板块全面升温。",
                "symbols": ["FOODMART", "BLUEGOLD", "CIVILBANK"],
                "tags": ["major", "consumer", "ma"],
                "truth_payload": {"impact": "up", "volatility": "high", "symbol": "FOODMART"},
                "parent_card_id": "default_food_event",
                "activation_prob": 0.65,
                "scheduled_at": _iso(360),
                "success_criteria": None,
                "failure_outcome": None,
                "scenario_id": "DEFAULT_TEMPLATE",
            },
        ],
    }
